version: 2
jobs:
  build:
    docker:
      - image: docker
    steps:
    - run:
      name: Install docker
      command: |
        apt-get update --fix-missing
        apt-get install -y apt-transport-https ca-certificates software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
        apt-key fingerprint 0EBFCD88
        add-apt-repository \
          "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) \
          stable"
        apt-get update
        apt-get install -y docker-ce
        docker --version
      - run:
          name: docker info
          command: docker info
      - run:
          name: docker build
          command: docker build -t helloworld .
      - run:
          name: run api
          command: docker run -d -p 5000:5000 helloworld; sleep 10
      - run:
          name: run api test
          command: curl --retry 10 --retry-delay 5 -v http://localhost:5000
