version: 2
jobs:
  build:
    docker:
      - image: docker
    steps:
      - checkout
      - run:
          name: docker info
          command: docker info
      - run:
          name: docker build
          command: docker build -t helloworld .
      - test
      - run:
          name: run api
          command: docker run -d -p 5000:5000 helloworld; sleep 10
      - run:
          name: run api test
          command: curl --retry 10 --retry-delay 5 -v http://localhost:5000
